# -*- coding: utf-8 -*-
"""Bienvenue dans Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import confusion_matrix, roc_curve, classification_report

data_path = r"c:\Users\hamza\OneDrive\Bureau\PROJET IA S8\creditcard.csv"
out_dir = r"C:\Users\hamza\.gemini\antigravity\brain\a1ee6439-c6e6-4940-bd9c-1a880b9f825b"

print("1. Loading Data...")
df = pd.read_csv(data_path)

print("2. Data Preparation (Scaling)...")
# Using RobustScaler because it is less prone to outliers (Amount has a lot of them)
rob_scaler = RobustScaler()

df['scaled_amount'] = rob_scaler.fit_transform(df['Amount'].values.reshape(-1,1))
df['scaled_time'] = rob_scaler.fit_transform(df['Time'].values.reshape(-1,1))

df.drop(['Time','Amount'], axis=1, inplace=True)

# Reorder columns to put scaled_amount and scaled_time at the beginning
scaled_amount = df['scaled_amount']
scaled_time = df['scaled_time']
df.drop(['scaled_amount', 'scaled_time'], axis=1, inplace=True)
df.insert(0, 'scaled_amount', scaled_amount)
df.insert(1, 'scaled_time', scaled_time)

X = df.drop('Class', axis=1)
y = df['Class']

print("3. Data Splitting...")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Training shape: {X_train.shape}, Test shape: {X_test.shape}")

print("4. Handling Imbalance (SMOTE)...")
sm = SMOTE(random_state=42)
X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)
print(f"SMOTE Training shape: {X_train_sm.shape}")

print("5. Training Models...")
models = {
    "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
    "RandomForest": RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42, n_jobs=-1)
}

results = []

fig_conf, axes_conf = plt.subplots(1, 3, figsize=(18, 5))
fig_roc, ax_roc = plt.subplots(figsize=(8, 6))

for idx, (name, model) in enumerate(models.items()):
    print(f"--> Training {name}...")
    model.fit(X_train_sm, y_train_sm)

    # Predict
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else model.decision_function(X_test)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)

    results.append({
        "Model": name, "Accuracy": acc, "Precision": prec, "Recall": rec, "F1-Score": f1, "AUC": auc
    })
    print(f"{name} -> Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f} | AUC: {auc:.4f}")

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes_conf[idx])
    axes_conf[idx].set_title(f'Confusion Matrix: {name}')
    axes_conf[idx].set_xlabel('Predicted')
    axes_conf[idx].set_ylabel('Actual')

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    ax_roc.plot(fpr, tpr, label=f"{name} (AUC = {auc:.4f})")

    # Save feature importances if possible
    if hasattr(model, 'feature_importances_'):
        plt.figure(figsize=(10,6))
        feat_importances = pd.Series(model.feature_importances_, index=X.columns)
        feat_importances.nlargest(15).plot(kind='barh')
        plt.title(f'Top 15 Feature Importances - {name}')
        plt.savefig(os.path.join(out_dir, f"feature_importance_{name.lower()}.png"), bbox_inches='tight')
        plt.close()

# Save Confusion Matrices
fig_conf.tight_layout()
fig_conf.savefig(os.path.join(out_dir, "confusion_matrices.png"), bbox_inches='tight')
plt.close(fig_conf)

# Save ROC Curves
ax_roc.plot([0, 1], [0, 1], 'k--')
ax_roc.set_xlabel('False Positive Rate')
ax_roc.set_ylabel('True Positive Rate')
ax_roc.set_title('ROC Curves')
ax_roc.legend(loc='lower right')
fig_roc.savefig(os.path.join(out_dir, "roc_curves.png"), bbox_inches='tight')
plt.close(fig_roc)

# Summary DataFrame
res_df = pd.DataFrame(results)
res_df.to_csv(os.path.join(out_dir, "model_results.csv"), index=False)
print("\n--- Final Results Summary ---")
print(res_df.to_string())
print("\nSuccessfully finished training and evaluation.")